<a href="https://colab.research.google.com/github/Sirada99/CE888/blob/master/CE888_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Lab1

In [0]:
import numpy as np


In [9]:

#1) Create a (4 x 2) integer array and print it's attributes
a = np.array([[2, 3, 4, 5],[6,8,11,7]])
print(a)

[[ 2  3  4  5]
 [ 6  8 11  7]]


In [26]:
#2) Create an array of dimension (1,10) and sort it in ascending and descending order
b=np.array([[11],[2],[1],[5],[4],[6],[7],[8],[9],[10]])
d=np.sort(b, axis = None) 
print(d)
f=d[::-1]
print(f)

[ 1  2  4  5  6  7  8  9 10 11]
[11 10  9  8  7  6  5  4  2  1]


In [29]:
#3) Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]
ar=[1,2,3,4,5,6,7,8,9] 
bb = np.reshape(ar, (-1, 3))
bb

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
#4) Stack two arrays of any size horizontally and vertically
w=np.array([[1, 2, 3],
       [4, 5, 6]])
e = np.array([[2, 3, 5],[6,8,7],[11,9,7]])
q=np.concatenate((w,e), axis=0)
print(q)
r=np.concatenate((w,e), axis=None)
print(r)

[[ 1  2  3]
 [ 4  5  6]
 [ 2  3  5]
 [ 6  8  7]
 [11  9  7]]
[ 1  2  3  4  5  6  2  3  5  6  8  7 11  9  7]


In [43]:
#5) Create two array of same size and find commom elements
h=np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
yy=np.array([[4, 2, 3],
       [4, 8, 6],
       [7, 10, 9]])
z=np.intersect1d(h, yy)
z

array([2, 3, 4, 6, 7, 8, 9])

In [49]:
#6) Create a 2D array of 5 by 5 and find the min and max values from each row and each column
k=np.array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 3],
           [11,10,9],
           [17,6, 4]])
mir=np.amin(k,axis=0)
print("minimum each row= ",mir)
mic=np.amin(k,axis=1)
print("minimum each column= ",mic)
mar=np.amax(k,axis=0)
print("maximum each row= ",mar)
mac=np.amax(k,axis=1)
print("maximum each column= ",mac)

minimum each row=  [1 2 3]
minimum each column=  [1 4 3 9 4]
maximum each row=  [17 10  9]
maximum each column=  [ 3  6  8 11 17]


In [58]:
#7) Create an array of size 100 and compute the mean, median, standard deviation.
np.random.seed(1)
xa = np.random.randint(200,size=(1,100))
print(xa)
mea=np.mean(xa)
print("Mean is: ",mea)
med=np.median(xa)
print("Median is: ",med)
st=np.std(xa)
print("standard deviation is: ",st)

[[ 37 140  72 137 133  79 192 144 129  71 134  25 178  20 101 146 139 156
  157 142  50  68  96  86 141 137   7  63  61  22  57   1 128  60   8 141
  115 175 121  30  71 131 198 149  49  57   3 196  24  43  76  26  52  80
  109 115  41  15  64 196  25 111 135  26 153 104  22   9 195 126  23 125
  100 155 165  57  83 166 136  32 162  10  23 143  87  25 199  92  74 190
   46 160 151 183  65 113  77   3 128   6]]
Mean is:  94.79
Median is:  94.0
standard deviation is:  57.646213232093565


In [59]:
#8) Normalize a 5x5 random matrix
op=np.array([[1, 2, 3,7,10],
           [4, 5, 6,2,13],
           [7, 8, 3,16,1],
           [11,10,9,4,2],
           [17,6, 4,7,18]])

cc=np.linalg.norm(op,ord=1)
print(cc)

44.0


In [65]:
#9) Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?
bbb= np.random.randint(10,size=(4,4,3))
bbc= np.random.randint(10,size=(4,4))
print("matrix bbb",bbb)
print("matrix bbc",bbc)
mul=np.dot(bbc,bbb)
print("matrix multiply",mul)

matrix bbb [[[5 9 6]
  [4 9 8]
  [7 5 1]
  [8 0 5]]

 [[3 9 0]
  [4 8 6]
  [2 4 3]
  [2 0 0]]

 [[4 2 5]
  [0 0 3]
  [8 5 3]
  [1 4 7]]

 [[3 2 2]
  [2 6 6]
  [0 1 5]
  [6 5 8]]]
matrix bbc [[8 5 5 7]
 [5 9 1 3]
 [9 3 3 3]
 [6 1 3 0]]
matrix multiply [[[151 142 128]
  [ 68 132  45]
  [ 79  69 119]
  [ 76  86 127]]

 [[ 92 131 118]
  [ 59 121  57]
  [ 31  27  76]
  [ 51  80  93]]

 [[102 123  96]
  [ 51 117  27]
  [ 63  45  84]
  [ 51  54  75]]

 [[ 55  78  47]
  [ 28  74  15]
  [ 48  27  42]
  [ 20  21  33]]]
